# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Verilog_FPGA_Design/Signal_Processing_Project/VGA_Wave_Show/VGA_Wave_Show.cache/wt [current_project]
set_property parent.project_path D:/Verilog_FPGA_Design/Signal_Processing_Project/VGA_Wave_Show/VGA_Wave_Show.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Verilog_FPGA_Design/Signal_Processing_Project/VGA_Wave_Show/VGA_Wave_Show.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/Verilog_FPGA_Design/Signal_Processing_Project/VGA_Wave_Show/VGA_Wave_Show.srcs/sources_1/imports/Wave_Coe/dds_1024x16b_wave.coe
add_files D:/Verilog_FPGA_Design/Signal_Processing_Project/VGA_Wave_Show/VGA_Wave_Show.srcs/sources_1/imports/Wave_Coe/dds_512x16b_wave.coe
add_files D:/Verilog_FPGA_Design/Signal_Processing_Project/VGA_Wave_Show/VGA_Wave_Show.srcs/sources_1/imports/Wave_Coe/dds_512x16b_wave_tan.coe
add_files D:/Verilog_FPGA_Design/Signal_Processing_Project/VGA_Wave_Show/VGA_Wave_Show.srcs/sources_1/imports/Wave_Coe/sine_wave.coe
read_verilog -library xil_defaultlib {
  D:/Verilog_FPGA_Design/Signal_Processing_Project/VGA_Wave_Show/VGA_Wave_Show.srcs/sources_1/new/VGA_Ctrl.v
  D:/Verilog_FPGA_Design/Signal_Processing_Project/VGA_Wave_Show/VGA_Wave_Show.srcs/sources_1/new/frame_control.v
  D:/Verilog_FPGA_Design/Signal_Processing_Project/VGA_Wave_Show/VGA_Wave_Show.srcs/sources_1/new/Top.v
}
read_ip -quiet D:/Verilog_FPGA_Design/Signal_Processing_Project/VGA_Wave_Show/VGA_Wave_Show.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all d:/Verilog_FPGA_Design/Signal_Processing_Project/VGA_Wave_Show/VGA_Wave_Show.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Verilog_FPGA_Design/Signal_Processing_Project/VGA_Wave_Show/VGA_Wave_Show.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all d:/Verilog_FPGA_Design/Signal_Processing_Project/VGA_Wave_Show/VGA_Wave_Show.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet D:/Verilog_FPGA_Design/Signal_Processing_Project/VGA_Wave_Show/VGA_Wave_Show.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all d:/Verilog_FPGA_Design/Signal_Processing_Project/VGA_Wave_Show/VGA_Wave_Show.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Verilog_FPGA_Design/Signal_Processing_Project/VGA_Wave_Show/VGA_Wave_Show.srcs/constrs_1/new/vgademo.xdc
set_property used_in_implementation false [get_files D:/Verilog_FPGA_Design/Signal_Processing_Project/VGA_Wave_Show/VGA_Wave_Show.srcs/constrs_1/new/vgademo.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Top -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_utilization_synth.rpt -pb Top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
